### ISSUE TITLE
Runtime error in asyncio from python3.8

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/system76-driver#158]
**Distribution (run `cat /etc/os-release`):**
 Pop!OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
20.04.9~1591719892~20.04~4518e0b --probably, but not confirmed

**Issue/Bug Description:**
Jun 09 20:15:18 pop-os system76-daemon[819]: 2020-06-09 20:15:18,126  INFO  Headphone volume adjustment not needed for 'oryp3-ess'
Jun 09 20:15:18 pop-os system76-daemon[819]: 2020-06-09 20:15:18,127  INFO  DPCD PWM fix not needed for 'oryp3-ess'
Jun 09 20:15:18 pop-os system76-daemon[819]: 2020-06-09 20:15:18,127  INFO  Limit Power Draw not needed 'oryp3-ess'
Jun 09 20:15:18 pop-os system76-daemon[819]: Exception ignored in: <function InputDevice.__del__ at 0x7f97948535e0>
Jun 09 20:15:18 pop-os system76-daemon[819]: Traceback (most recent call last):
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
Jun 09 20:15:18 pop-os system76-daemon[819]:     self.close()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
Jun 09 20:15:18 pop-os system76-daemon[819]:     super().close()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
Jun 09 20:15:18 pop-os system76-daemon[819]:     loop = asyncio.get_event_loop()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
Jun 09 20:15:18 pop-os system76-daemon[819]:     raise RuntimeError('There is no current event loop in thread %r.'
Jun 09 20:15:18 pop-os system76-daemon[819]: RuntimeError: There is no current event loop in thread 'Dummy-1'.
Jun 09 20:15:18 pop-os system76-daemon[819]: Exception ignored in: <function InputDevice.__del__ at 0x7f97948535e0>
Jun 09 20:15:18 pop-os system76-daemon[819]: Traceback (most recent call last):
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
Jun 09 20:15:18 pop-os system76-daemon[819]:     self.close()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
Jun 09 20:15:18 pop-os system76-daemon[819]:     super().close()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
Jun 09 20:15:18 pop-os system76-daemon[819]:     loop = asyncio.get_event_loop()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
Jun 09 20:15:18 pop-os system76-daemon[819]:     raise RuntimeError('There is no current event loop in thread %r.'
Jun 09 20:15:18 pop-os system76-daemon[819]: RuntimeError: There is no current event loop in thread 'Dummy-1'.
Jun 09 20:15:18 pop-os system76-daemon[819]: Exception ignored in: <function InputDevice.__del__ at 0x7f97948535e0>
Jun 09 20:15:18 pop-os system76-daemon[819]: Traceback (most recent call last):
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 159, in __del__
Jun 09 20:15:18 pop-os system76-daemon[819]:     self.close()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 304, in close
Jun 09 20:15:18 pop-os system76-daemon[819]:     super().close()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 54, in close
Jun 09 20:15:18 pop-os system76-daemon[819]:     loop = asyncio.get_event_loop()
Jun 09 20:15:18 pop-os system76-daemon[819]:   File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
Jun 09 20:15:18 pop-os system76-daemon[819]:     raise RuntimeError('There is no current event loop in thread %r.'
Jun 09 20:15:18 pop-os system76-daemon[819]: RuntimeError: There is no current event loop in thread 'Dummy-1'.

**Expected behavior:**
No crash

**Other Notes:**
Investigating other issues with this system as it fails to complete a boot (but gets to a desktop).

**Comment by leviport** [comment]
Pretty sure this got fixed at some point
